import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Briefcase,HomeIcon, MessageCircle,  Star, UserCircle,  } from "lucide-react";
import { FloatingNav } from "@/components/ui/floating-navbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navItems = [
  {
    name: "Home",
    link: "/",
    icon: <HomeIcon className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "About",
    link: "#about",
    icon: <UserCircle className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Projects",
    link: "#projects",
    icon: 
      <Briefcase className="h-4 w-4 text-neutral-500 dark:text-white" />
  },

  {
    name: "Skills",
    link: "#skills",
    icon: 
      <Star className="h-4 w-4 text-neutral-500 dark:text-white" />
  },
  {
    name: "Contact",
    link: "#contact",
    icon: 
      <MessageCircle className="h-4 w-4 text-neutral-500 dark:text-white" />
  },
  
];
  

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FloatingNav navItems={navItems}/>
        {children}
       
      </body>
    </html>
  );
}
